default_agent: github-mcp-server 
agents:
  github-mcp-server:
    name: github-mcp-server
    entrypoint: "server.py"
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::722141136946:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-2-0d6e4079e3
      execution_role_auto_create: false
      account: '722141136946'
      region: ap-southeast-2
      ecr_repository: null
      ecr_auto_create: true 
      network_configuration:
        network_mode: PUBLIC
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    oauth_configuration: null
