[project]
name = "github-mcp-agentcore"
version = "0.1.0"
description = "GitHub MCP server adapter for Amazon Bedrock AgentCore"
requires-python = ">=3.10"
dependencies = [
    "bedrock-agentcore",
    "bedrock-agentcore-starter-toolkit",
    "fastmcp",
    "uvicorn",
]